stages:
  - build
  - deploy

build:
   stage: build
   #when: manual
   only:
       - tags
   script:
      - mkdir -p dist
      #- npm install @mui/material @emotion/react @emotion/styled
      - npm install  react-dates --legacy-peer-deps
      - CI= npm run build
      - ls
      - echo "Build Successfully"
   artifacts:
       paths:
         - build/
       expire_in: 1 hour
   only:
    - main    


deploy:
   stage: deploy
   #when: manual
   image:
     name: amazon/aws-cli
     entrypoint: [""]
   dependencies:
     - build
   script:
     - aws --version
     - aws s3 cp --acl public-read --recursive build s3://eservz-dev
     - echo "deployed successfully"
   only:
    - main
