import { makeStyles } from '@material-ui/core';

export default makeStyles((theme) => ({
  wrapper: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    background: "#FFFCFC",
    [theme.breakpoints.down('xs')]: {
      display:"flex",
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      paddingLeft:"40px",   
      width:"100vw",


    },
    [theme.breakpoints.down('sm')]: {
      display:"flex",
      flexDirection: 'column',
      flexWrap: "wrap",
      alignItems: 'center',
      justifyContent: 'center',   
      width:"100%",


    },
  },
  img: {
    width: "30%",
    position: "relative",
    [theme.breakpoints.down('xs')]: {
      width: "100%",
    },
    [theme.breakpoints.down('sm')]: {
      width: "80%",
    },
  },
  imageTextPara: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    padding: "0px 1px",
    gap: "8px",
    height: "173px",
    width: "120px",
  },
  innerWrapper: {
    display: 'flex',
    flexWrap: 'wrap',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    gap: "30px",
    alignItems: "center",
    background: "#FFFCFC",
    position: "relative",
  },
  items: {
    display: 'flex',
    flexWrap: 'wrap',
    flexDirection: 'row',
    justifyContent: "space-between",
    gap: '80px',
    background: "#FFFCFC",[theme.breakpoints.down('xs')]: {
      flexDirection:"column",
    },
  },
  monitor: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: "30px",
    background: "#FFFCFC",
    position: "relative",
  },
  index:{
    zIndex:7,
  },
  pair: {
    display: "flex",
    flexDirection:"row",
    // flexWrap: "wrap",
    gap: "20px",
  },
  firstRow: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    flexWrap: "wrap",
    padding: "0px",
    gap: "20px",
    marginTop: "95px",
    zIndex:1,
  },
  secondRow: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    padding: "23px 33px",
    gap: "20px",
    width: "100%",
    maxWidth: "368px",
    height: "565px",
    background: "#FFFFFF",
    boxShadow: "0px 4px 4px rgba(0, 0, 0, 0.08)",
    zIndex:1,
    borderRadius: "16px",
    [theme.breakpoints.down('xs')]: {
      maxWidth: "100%",
      marginBottom: "20px",
    },
  },
  input: {
    width: "282px",
    height: "36px",
    left: "16px",
    radius: "4px",
    padding: "14px, 16px, 14px, 16px",
    gap: "10px",
    zIndex:1,
  },
  thirdRow: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "23px 33px",
    gap: "20px",
    width: "100%",
    maxWidth: "368px",
    height: "565px",
    background: "#FFFFFF",
    boxShadow: "0px 4px 4px rgba(0, 0, 0, 0.08)",
    borderRadius: "16px",
    zIndex:1, 
    marginBottom: "0px",
    [theme.breakpoints.down('xs')]: {
      maxWidth: "100%",
      marginBottom: "20px",
    },
  },
  twoContainer: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'center',
    gap: '120px',
    background: '#FFFCFC',
    position:"relative",
    [theme.breakpoints.down('xs')]: {
      flexDirection: 'column',
      alignItems: 'center',
    },
    [theme.breakpoints.down('sm')]: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      flexWrap: 'nowrap',
    },
  },
  innerTwoContainer: {
    display: 'flex',
    flexWrap: 'wrap',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    gap: '40px',
    background: '#FFFFFF',
    padding: '30px',
    boxShadow: '0px 4px 4px rgba(0, 0, 0, 0.08)',
    borderRadius: '12px',
    zIndex:1,
  },
  innerThirdContainer: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'center',
    gap: '30px',
  },
  fifthContainer: {
    display: 'flex',
    flexWrap: 'wrap',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    gap: '30px',
    position:"relative",
  },
  fifthInner: {
    width: '90%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'flex-start',
    padding: '0px',
    marginBottom: '150px',
    gap: '120px',
    [theme.breakpoints.down('xs')]: {
      flexDirection: 'column',
      alignItems: 'center',
      flexWrap: 'wrap',
    },
    [theme.breakpoints.down('sm')]: {
      flexDirection: 'row',
      width:"100%",
    },
  },
  fifthHeading: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  fonts: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    padding: '0px',
    // flexWrap: 'wrap',
    gap: '24px',
    width: '332px',
    height: '180px',
    [theme.breakpoints.down('sm')]: {
      flexDirection: 'row',
      width:"290px",
      flexWrap: 'wrap',
    },
  },
  sixthContainer: {
    display: 'flex',
    justifyContent: 'center',
    gap: '40px',
    alignItems: 'center',
    [theme.breakpoints.down('xs')]: {
        width: '100%',
        maxWidth: '400px',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        paddingLeft:"30px"
      },
      [theme.breakpoints.down('sm')]: {
        width: '100%',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        paddingLeft:"30px"
      },
  },
  sixthRight: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    gap: '50px',
    width: '565px',
    height: '152px',
    textAlign: 'center',
    marginBottom: '40px',
    [theme.breakpoints.down('xs')]: {
      width: '100%',
      maxWidth: '400px',
    },
  },
  innerSeventh: {
    marginTop: '20px',
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: '70px',
    [theme.breakpoints.down('xs')]: {
        width: '100%',
        maxWidth: '400px',
      },
      [theme.breakpoints.down('sm')]: {
        width: '90%',
        maxWidth: '280px',
      
      },
  },imageLines1:{
    position:"absolute",
    left:"10%",
    bottom:"-24%",
    zIndex:1
  },
  imageLines7:{
    position:"absolute",
    left:"48%",
    bottom:"10%",
    zIndex:1,
    width:"20px",
    height:"20px"
  },
  heroRock:{
    position:"absolute",
    top:"7%",
    left:"15%",
    width:"60px",
    height:"80px",

  },
  imageLines:{
    position: 'absolute',
    left:0,
    top:"-100px",
   zIndex:1,
  },
  imageLines2:{
    position: 'absolute',
    left:"-5%",
   zIndex:1,
  },
  heroCircle:{
    position:"absolute",
    width:"80%",
    height:"80%",
    top:"0",
    right:"15%",
    zIndex:-1,
  },
  imageLines3:{
    position: 'absolute',
    zIndex:-1,
    width:"60%",
    height:"90%",
    left:"0",
    top:"0",   
  },
  imageLines8:{
    position: 'absolute',
    top:"-10%",
    right:"10%",
    height:"67px",
    width:"75px",
    zIndex:1,
  },
  imageLines9:{
    position: 'absolute',
    top:"15%",
    right:"20%",
    height:"34px",
    width:"34px",
   zIndex:1,
  },
  imageLines10:{
    position: 'absolute',
    top:"0",
    left:"20%",
    height:"28px",
    width:"28px",
   zIndex:1,
  },
  imageLines11:{
    position:"absolute",
    left:"-20px",
    bottom:"0",
    zIndex:-1,
    height:"300px",
    width:"100%"
  },
  imageLines4:{
    // alignSelf:"flex-start",
    position: 'absolute',
    left:"3%",
    bottom:"10%",
    zIndex:1,
   [theme.breakpoints.down('xs')]: {
    zIndex:"-1",
  },
  }
}));